/* Molnsynk för Att göra lista. Firebase web API-nyckeln är en offentlig appidentifierare;
   åtkomsten skyddas av Firebase Authentication och Firestore-regler. */
(()=>{
  if(!window.firebase)return;
  const firebaseConfig={apiKey:'AIzaSyB7gHnwaDCTIRrK7vE2NjkntNE4Tb60kjQ',authDomain:'todo-list-aff74.firebaseapp.com',projectId:'todo-list-aff74',storageBucket:'todo-list-aff74.firebasestorage.app',messagingSenderId:'836194978024',appId:'1:836194978024:web:5f9679bd917810f8e5e15d'};
  firebase.initializeApp(firebaseConfig);
  const auth=firebase.auth(),db=firebase.firestore(),provider=new firebase.auth.GoogleAuthProvider();
  provider.setCustomParameters({prompt:'select_account'});
  document.head.insertAdjacentHTML('beforeend','<style>.sync-card{display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:12px;padding:12px 14px;margin:12px 0 0;border:1px solid var(--l);border-radius:15px;background:var(--t)}.sync-user{display:flex;align-items:center;gap:10px;min-width:0}.sync-user>div{min-width:0}.sync-avatar{display:grid;place-items:center;width:38px;height:38px;flex:0 0 38px;overflow:hidden;border-radius:50%;background:var(--p);font-size:1rem}.sync-avatar img{width:100%;height:100%;object-fit:cover}.sync-card b{display:block;font-size:.88rem}.sync-card small{display:block;color:var(--m);margin-top:2px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.sync-email{font-size:.76rem}.side-menu .sync-card{grid-template-columns:1fr}.side-menu .sync-card button{width:100%;margin:0;min-height:40px;white-space:nowrap;background:var(--p);color:var(--i)}.side-menu .sync-card .sync-google{background:var(--v);color:#fff}@media(max-width:430px){.sync-card{grid-template-columns:1fr}}</style>');
  const syncCard=document.createElement('section');syncCard.className='sync-card';syncCard.id='sync-card';syncCard.innerHTML='<div class="sync-user"><span class="sync-avatar" id="sync-avatar">☁️</span><div><b id="sync-title">Synka mellan enheter</b><small class="sync-email" id="sync-email" hidden></small><small id="sync-status">Logga in för att se samma lista på telefon och dator.</small></div></div><button class="sync-google" id="sync-login">Fortsätt med Google</button>';
  document.querySelector('#side-menu').append(syncCard);
  const title=document.querySelector('#sync-title'),email=document.querySelector('#sync-email'),avatar=document.querySelector('#sync-avatar'),status=document.querySelector('#sync-status'),login=document.querySelector('#sync-login');
  let unsubscribe=null,remoteReady=false,applyingRemote=false,lastSyncedSignature=null,lastSyncedAt=Number(localStorage.getItem('todo-last-synced-at')||0);
  const plainTasks=()=>T.map(({marked,...task})=>task),documentFor=user=>db.collection('users').doc(user.uid).collection('todo').doc('state'),setStatus=text=>status.textContent=text;
  function showSyncStatus(){if(!navigator.onLine){setStatus('⚠️ Ingen anslutning — synkar automatiskt senare.');return}if(!lastSyncedAt){setStatus('Synkar din lista …');return}const seconds=Math.floor((Date.now()-lastSyncedAt)/1000),when=seconds<60?'nyss':seconds<3600?`för ${Math.floor(seconds/60)} min sedan`:seconds<86400?`för ${Math.floor(seconds/3600)} tim sedan`:`för ${Math.floor(seconds/86400)} dag sedan`;setStatus(`Synkad ✓ · ${when}`)}
  function markSynced(){lastSyncedAt=Date.now();localStorage.setItem('todo-last-synced-at',String(lastSyncedAt));showSyncStatus()}
  const originalSave=save;
  async function pushState(){const user=auth.currentUser;if(!user||!remoteReady||applyingRemote)return;if(!navigator.onLine){showSyncStatus();return}const tasks=plainTasks(),signature=JSON.stringify(tasks);if(signature===lastSyncedSignature)return;setStatus('Synkar ändringar …');try{await documentFor(user).set({tasks,updatedAt:firebase.firestore.FieldValue.serverTimestamp()});lastSyncedSignature=signature;markSynced()}catch(error){console.warn('Kunde inte synka listan',error);setStatus('Kunde inte synka just nu — ändringarna finns kvar på enheten.')}}
  save=function(){originalSave();pushState()};
  login.onclick=async()=>{try{if(auth.currentUser){await auth.signOut();return}setStatus('Öppnar Google-inloggning …');await auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL);await auth.signInWithPopup(provider)}catch(error){console.warn('Google-inloggningen misslyckades',error);const message=error?.code==='auth/unauthorized-domain'?'Webbadressen saknar behörighet i Firebase. Kontrollera Authorized domains.':error?.code==='auth/network-request-failed'?'Kontrollera internetanslutningen och försök igen.':`Inloggningen kunde inte öppnas (${error?.code||'okänt fel'}).`;setStatus(message)}};
  auth.onAuthStateChanged(async user=>{if(unsubscribe){unsubscribe();unsubscribe=null}remoteReady=false;lastSyncedSignature=null;if(!user){title.textContent='Synka mellan enheter';email.hidden=true;avatar.replaceChildren();avatar.textContent='☁️';login.textContent='Fortsätt med Google';login.className='sync-google';setStatus('Logga in för att se samma lista på telefon och dator.');return}title.textContent='Du är inloggad';email.textContent=user.email||'';email.hidden=!user.email;avatar.replaceChildren();if(user.photoURL){const image=new Image();image.src=user.photoURL;image.alt='Din profilbild';avatar.append(image)}else avatar.textContent='👤';login.textContent='Logga ut';login.className='';showSyncStatus();const ref=documentFor(user);try{const first=await ref.get();if(!first.exists)await ref.set({tasks:plainTasks(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});remoteReady=true;unsubscribe=ref.onSnapshot(snapshot=>{if(!snapshot.exists)return;const cloudTasks=Array.isArray(snapshot.data().tasks)?snapshot.data().tasks:[];lastSyncedSignature=JSON.stringify(cloudTasks);applyingRemote=true;T=cloudTasks.map(task=>({...task,marked:false}));originalSave();render();applyingRemote=false;markSynced()},error=>{console.warn('Kunde inte läsa synkad lista',error);setStatus('Synkning saknar behörighet.')})}catch(error){console.warn('Kunde inte starta synkningen',error);setStatus('Kunde inte starta synkningen. Kontrollera internet och behörighet.')}});
  window.addEventListener('offline',()=>{if(auth.currentUser)showSyncStatus()});window.addEventListener('online',()=>{if(auth.currentUser){setStatus('Ansluten — synkar ändringar …');pushState()}});setInterval(()=>{if(auth.currentUser)showSyncStatus()},30000);auth.getRedirectResult().catch(error=>{console.warn('Kunde inte slutföra Google-inloggningen',error);setStatus(`Inloggningen kunde inte slutföras (${error?.code||'okänt fel'}).`)});
})();

/* Välkomstsida och konto-inloggning. Firebase använder e-postadressen som
   kontoidentifierare, vilket gör att samma konto fungerar på alla enheter. */
(()=>{
  if(!window.firebase)return;
  const auth=firebase.auth();
  document.head.insertAdjacentHTML('beforeend',`<style>
    .signed-out .app{display:none}.welcome-screen{min-height:100vh;padding:28px 16px 52px;background:radial-gradient(circle at top left,#a99bff 0,#6c4cff 34%,#272040 82%);color:#fff}.welcome-wrap{width:min(980px,100%);margin:auto}.welcome-brand{display:flex;align-items:center;gap:9px;font-weight:900;font-size:1.05rem}.welcome-brand i{font-style:normal;display:grid;place-items:center;width:32px;height:32px;border-radius:10px;background:#fff;color:#6c4cff}.welcome-grid{display:grid;grid-template-columns:1.15fr .85fr;gap:34px;align-items:center;margin-top:48px}.welcome-copy h1{font-size:clamp(2.35rem,7vw,4.3rem);line-height:1.02;letter-spacing:-.055em;margin:0;max-width:620px}.welcome-copy>p{font-size:1.08rem;line-height:1.65;color:#e6e1ff;max-width:570px;margin:18px 0 0}.welcome-features{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:28px;max-width:620px}.welcome-feature{padding:14px;border:1px solid #ffffff24;border-radius:16px;background:#ffffff12}.welcome-feature b{display:block;font-size:.92rem;margin-top:7px}.welcome-feature span{display:block;color:#e6e1ff;font-size:.8rem;line-height:1.35;margin-top:3px}.auth-box{color:#26203c;background:#fff;border-radius:24px;padding:23px;box-shadow:0 20px 60px #160d3b66}.auth-box h2{margin:0;font-size:1.45rem}.auth-box>p{margin:6px 0 18px;color:#716a86;font-size:.9rem}.auth-tabs{display:grid;grid-template-columns:1fr 1fr;background:#eeeaff;padding:4px;border-radius:12px;margin-bottom:14px}.auth-tabs button{min-height:38px;background:transparent;color:#756d90}.auth-tabs button.active{background:#fff;color:#5c3fe1;box-shadow:0 2px 8px #3e2b7514}.auth-form{display:grid;gap:10px}.auth-form label{display:grid;gap:5px;font-size:.82rem;font-weight:800;color:#5b5471}.auth-form input{border:2px solid #e6e1f1;color:#29223e;background:#fff}.auth-main,.auth-google{width:100%;min-height:48px}.auth-main{background:#6c4cff;color:#fff}.auth-google{background:#f1edff;color:#543ad1}.auth-separator{display:flex;align-items:center;gap:9px;color:#968faa;font-size:.78rem;margin:3px 0}.auth-separator:before,.auth-separator:after{content:'';height:1px;flex:1;background:#e4dff0}.auth-status{min-height:20px;margin:2px 0 0;color:#766f89;font-size:.8rem;line-height:1.35}.auth-status.error{color:#b02f4d}.auth-terms{margin:3px 0 0;color:#938ca4;font-size:.72rem;line-height:1.4}@media(max-width:720px){.welcome-screen{padding-top:20px}.welcome-grid{grid-template-columns:1fr;margin-top:34px;gap:27px}.welcome-copy h1{max-width:520px}.auth-box{max-width:510px}.welcome-features{grid-template-columns:1fr 1fr}}@media(max-width:380px){.welcome-features{grid-template-columns:1fr}.welcome-copy h1{font-size:2.25rem}}
  </style>`);
  const screen=document.createElement('main');
  screen.className='welcome-screen';screen.id='welcome-screen';screen.hidden=true;
  screen.innerHTML=`<div class="welcome-wrap"><div class="welcome-brand"><i>✓</i> Att göra lista</div><div class="welcome-grid"><section class="welcome-copy"><h1>Få mer gjort,<br>med mindre stress.</h1><p>Samla allt du vill få gjort på ett ställe. Planera dagen, håll fokus och bocka av när det är klart.</p><div class="welcome-features"><div class="welcome-feature">📝<b>Smarta listor</b><span>Samla och bocka av uppgifter.</span></div><div class="welcome-feature">🎯<b>Fokus & prioritet</b><span>Välj det som är viktigast just nu.</span></div><div class="welcome-feature">🔔<b>Datum & påminnelser</b><span>Håll koll på vad som närmar sig.</span></div><div class="welcome-feature">☁️<b>Synka tryggt</b><span>Samma lista på mobil och dator.</span></div></div></section><section class="auth-box" aria-label="Logga in"><h2 id="auth-heading">Välkommen tillbaka</h2><p id="auth-intro">Logga in för att öppna din personliga lista.</p><div class="auth-tabs"><button type="button" class="active" data-auth-mode="login">Logga in</button><button type="button" data-auth-mode="signup">Skapa konto</button></div><form class="auth-form" id="email-auth-form"><label>E-postadress<input id="auth-email" type="email" autocomplete="email" placeholder="namn@exempel.se" required></label><label>Lösenord<input id="auth-password" type="password" autocomplete="current-password" minlength="6" placeholder="Minst 6 tecken" required></label><button class="auth-main" id="email-auth-submit">Logga in</button></form><div class="auth-separator">eller</div><button type="button" class="auth-google" id="welcome-google">Fortsätt med Google</button><p class="auth-status" id="auth-status" role="status"></p><p class="auth-terms">Dina listor sparas säkert i ditt eget konto och kan öppnas på flera enheter.</p></section></div></div>`;
  document.body.prepend(screen);
  const app=document.querySelector('.app'),form=screen.querySelector('#email-auth-form'),email=screen.querySelector('#auth-email'),password=screen.querySelector('#auth-password'),submit=screen.querySelector('#email-auth-submit'),heading=screen.querySelector('#auth-heading'),intro=screen.querySelector('#auth-intro'),status=screen.querySelector('#auth-status');
  let mode='login';
  const showStatus=(message,error=false)=>{status.textContent=message;status.classList.toggle('error',error)};
  const setBusy=busy=>{submit.disabled=busy;screen.querySelector('#welcome-google').disabled=busy;submit.textContent=busy?'Vänta …':mode==='login'?'Logga in':'Skapa konto'};
  const describeError=error=>({
    'auth/invalid-email':'Kontrollera e-postadressen.',
    'auth/invalid-credential':'Fel e-postadress eller lösenord.',
    'auth/user-not-found':'Fel e-postadress eller lösenord.',
    'auth/wrong-password':'Fel e-postadress eller lösenord.',
    'auth/email-already-in-use':'Det finns redan ett konto med den e-postadressen. Välj Logga in.',
    'auth/weak-password':'Lösenordet behöver vara minst 6 tecken.',
    'auth/operation-not-allowed':'E-post och lösenord behöver aktiveras i Firebase Authentication först.',
    'auth/too-many-requests':'För många försök. Vänta en stund och försök igen.',
    'auth/network-request-failed':'Kontrollera internetanslutningen och försök igen.'
  }[error?.code]||'Inloggningen kunde inte genomföras. Försök igen.');
  screen.querySelectorAll('[data-auth-mode]').forEach(button=>button.onclick=()=>{mode=button.dataset.authMode;screen.querySelectorAll('[data-auth-mode]').forEach(item=>item.classList.toggle('active',item===button));heading.textContent=mode==='login'?'Välkommen tillbaka':'Skapa ditt konto';intro.textContent=mode==='login'?'Logga in för att öppna din personliga lista.':'Börja planera på mobil och dator.';password.autocomplete=mode==='login'?'current-password':'new-password';setBusy(false);showStatus('')});
  form.onsubmit=async event=>{event.preventDefault();setBusy(true);showStatus(mode==='login'?'Loggar in …':'Skapar konto …');try{await auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL);if(mode==='login')await auth.signInWithEmailAndPassword(email.value.trim(),password.value);else await auth.createUserWithEmailAndPassword(email.value.trim(),password.value)}catch(error){console.warn('E-postinloggning misslyckades',error);showStatus(describeError(error),true)}finally{setBusy(false)}};
  screen.querySelector('#welcome-google').onclick=async()=>{setBusy(true);showStatus('Öppnar Google-inloggning …');try{const google=new firebase.auth.GoogleAuthProvider();google.setCustomParameters({prompt:'select_account'});await auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL);await auth.signInWithPopup(google)}catch(error){console.warn('Google-inloggning misslyckades',error);showStatus(describeError(error),true)}finally{setBusy(false)}};
  auth.onAuthStateChanged(user=>{const signedOut=!user;document.body.classList.toggle('signed-out',signedOut);screen.hidden=!signedOut;if(app)app.setAttribute('aria-hidden',String(signedOut));if(signedOut){password.value='';showStatus('')}});
})();
